### ISSUE TITLE
Question: Expansion module that adds objects

### ISSUE THREAD

**Issue by kx499** [MISP/misp-modules#142]
Does anyone have any examples of expansion modules that leverage objects? I'm not sure what that would look like or if its even supported.

**Comment by adulau** [comment]
We need to update the modules API to support the objects. It's planned.

**Comment by kx499** [comment]
Any word on this one yet?

**Comment by andurin** [comment]
I came across this issue with the question if modules may help to transform attributes to objects within a event.

f.e: transform an url attribute to an url object dissecting the different parts of the url.

**Comment by chrisr3d** [comment]
For now I will close this issue since I think all the requests have been processed and the features requested are supported, but please have a look at the following details below:

@kx499 This feature has been implemented this year and is supported for a couple of months now, in some specific modules where it really made sense to have it, without breaking the old one. If you see any use case where it would make sense that a module produces some MISP objects, feel free to submit a pull request or a feature request in this issue or a new one. 
I will soon release some documentation on how to contribute modules like this.

@andurin You can merge attributes into objects withing the UI, it is a recent feature we added in MISP

**Comment by andurin** [comment]
> @andurin You can merge attributes into objects withing the UI, it is a recent feature we added in MISP

Love this!
