### ISSUE TITLE
Testing / Troubleshooting - misp-modules

### ISSUE THREAD

**Issue by giray** [MISP/misp-modules#34]
I can see via curl that modules are installed and running.  However, I do not see any traffic from MISP itself.  How do I trigger MISP to connect to misp-modules?  

I do have it configured under 'Plugin Settings'  with the following values

* Plugin.Enrichment_services_enable	true
* Plugin.Enrichment_hover_enable	true
* Plugin.Enrichment_timeout	5
* Plugin.Enrichment_hover_timeout	2
* Plugin.Enrichment_services_url	http://127.0.0.1
* Plugin.Enrichment_services_port 6666

**Comment by iglocska** [comment]
Hmph that is odd. Basically if you have it running it should query /modules on misp-modules each time you:

- View an event
- Go to the Plugin tab of the server settings

**Comment by hazmalware** [comment]
I am seeing the same thing. Here is my setup:

> Currently installed version..... v2.4.49
> Latest available version..... v2.4.49	
> Status..... OK

I have installed the latest version of modules. I have tested with the curl command and am able to retrieve the modules JSON showing installed versions.

I have further confirmed that it is connecting to the modules URL when i hit the event page via netstat:
```
root@misp:/var/www/MISP/app# netstat -pano | grep 6666
tcp        0      0 127.0.0.1:6666          0.0.0.0:*               LISTEN      1492/python3     off (0.00/0/0)
tcp        0      0 127.0.0.1:40803         127.0.0.1:6666          TIME_WAIT   -                timewait (19.78/0/0)
tcp        0      0 127.0.0.1:40805         127.0.0.1:6666          ESTABLISHED 1919/apache2     off (0.00/0/0)
tcp        0      0 127.0.0.1:6666          127.0.0.1:40805         ESTABLISHED 1492/python3     off (0.00/0/0)
tcp6       0      0 ::1:6666                :::*                    LISTEN      1492/python3     off (0.00/0/0)
```

When i view the event page I do not see the "*" asterisk next to the attribute and hover is not working. I have also noticed some lag when navigating through the UI since I have installed and enabled the enrichment. I have tried rebooting the MISP server, restarting mysql, apache, and redis with no results.

**Comment by giray** [comment]
I' now at 

Currently installed version..... v2.4.50	
Latest available version..... v2.4.50	

.. and the enrichment plugin settings are correct.  Also using curl, and the json example I can do dns lookups. However,  MIPS itself does no attempts to connect. 

Still looking for any way to troubleshoot ...

**Comment by iglocska** [comment]
What OS are you on? Is it Red hat / CentOS by any chance?
