### ISSUE TITLE
MODULE API NOT WORKING : {'name': 'Module not found or not available.', 'message': 'Module not found or not available.', 'url': '/modules/queryEnrichment'}

### ISSUE THREAD

**Issue by Alaa-HIjazi** [MISP/misp-modules#404]
This template is meant for bug reports, if you have a feature request user the other template.
If you would like to report a bug, please fill the template bellow

Work environment
Questions	Answers
Type of issue	No Module Found
OS version (server)	Ubuntu
OS version (client)	Win10
PHP version	7.4
MISP version / git hash	2.4.125 (4604aa4)
Browser	Firefox
Expected behavior
When Using CURL: curl -k --header "Authorization: Api key" --header "Accept: application/json" --header "Content-Type: application/json" --data @event.json -X POST https://misp.local/modules/queryEnrichment

and event.json is:
{
"domain": "Test.com",
"module": "virustotal"
}
it should get as a response json format, because with securitytrails module it's working fine
Moreover, otx, whois, Are not working too with the same error below

Actual behavior
What i'am receiving is an error :
{'name': 'Module not found or not available.', 'message': 'Module not found or not available.', 'url': '/modules/queryEnrichment'}

**Comment by chrisr3d** [comment]
This module uses another input format, pretty similar, but with a slight change concerning the attribute itself:
Instead of passing your attribute type and its value like you did with `domain: test.com`, it requires an actual attribute.

Example of valid input format:
```
{
    "module": "virustotal",
    "attribute": {
        "type": "domain",
        "value": "test.com",
        "uuid": "_YOUR_ATTRIBUTE_UUID_"
    },
    "config": {
        "apikey": "_YOUR_VIRUSTOTAL_API_KEY_"
    }
}
```
Note that the attribute uuid is probably required as well to make available the potential references to the input attribute.
Also, the virustotal API key will be required and would have been the next issue you could have faced if you did not face this one first.

On my side I will check all the modules which are in the same case and patch their error message for more clarity

**Comment by Alaa-HIjazi** [comment]
Hello Chris, Okay it will be great since it's not only with virustotal, but recently when the last version was released some modules seems to work, which is good like otx.
Thank you

**Comment by chrisr3d** [comment]
I just pushed some changes to get better error messages, feel free to test if everything is working. If not, you should at least get some clearer error messages so I can try to reproduce any issue and fix it.
Let me know if anything else goes wrong

**Comment by Alaa-HIjazi** [comment]
Okay Great, Thank you Chris ! Will do if i encounter Any other issues
